[package]
name = "scopie"
version = "0.1.0"
authors = ["khyperia <khyperia@live.com>"]
edition = "2018"

[dependencies]
anyhow = "*"
dirs = "*"
eframe = "*"
png = "*"
regex = "*"
serialport = "*"
time = { version = "*", features = ["local-offset", "formatting", "macros"] }
